import React from "react";
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import FeaturedImage from "../components/FeaturedImage";
import Navigation from "../components/Nav/Navigation";
import Footer from "../components/Footer/Footer";
import BlogItem from "../components/Blog/BlogItem";
import Layout from "../components/Layout/Layout";

export default function Home({ posts }) {
  // console.log(posts);
  posts?.map((post) => console.log(post.id));

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <h1 class="font-medium leading-tight text-5xl mt-0 mb-2 text-blue-600 text-center">
          Welcome to Sandy's Blog!
        </h1>
        <div class="grid grid-rows-4 grid-flow-col gap-4 sm:grid-rows-1  md:grid-rows-3">
          {posts.length &&
            posts.slice(0, 6).map((post) => {
              return <BlogItem key={post.id} post={post} />;
            })}
        </div>
      </Layout>
    </div>
  );
}

export async function getServerSideProps() {
  // Fetch data from external API
  const res = await fetch(`http://www.wpdemo.local/wp-json/wp/v2/posts/`);
  const posts = await res.json();

  // Pass data to the page via props
  return { props: { posts } };
}
